:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:schedule:
  expire_carts_job:
    cron: "0 * * * *" # Executa a cada 1 hora
    class: "ExpireCartsJob"
